Drop pkg-config dependency. Script now guesses prefix from location of jags, and user may override with configure options or environment variables.
Cleanup script removes files built by configure

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -613,19 +613,16 @@ LIBS
 build_alias
 host_alias
 target_alias
-PKG_CONFIG
-JAGS_CFLAGS
-JAGS_LIBS
-JAGS_MODDIR
+ac_prefix_program
+JAGS_INCLUDE
+JAGS_LIB
+JAGS_MODULES
 LIBOBJS
 LTLIBOBJS'
 ac_subst_files=''
       ac_precious_vars='build_alias
 host_alias
-target_alias
-PKG_CONFIG
-JAGS_CFLAGS
-JAGS_LIBS'
+target_alias'
 
 
 # Initialize some variables set by options.
@@ -1196,15 +1193,12 @@ if test -n "$ac_init_help"; then
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
-  --with-jags=JAGS_HOME   the location of the JAGS pkgconfig file
-
-Some influential environment variables:
-  PKG_CONFIG  path to pkg-config utility
-  JAGS_CFLAGS C compiler flags for JAGS, overriding pkg-config
-  JAGS_LIBS   linker flags for JAGS, overriding pkg-config
-
-Use these variables to override the choices made by `configure' or to help
-it to find libraries and programs with nonstandard names/locations.
+  --with-jags-include=INCLUDE_PATH
+                          the location of JAGS header files
+  --with-jags-lib=LIB_PATH
+                          the location of the JAGS library
+  --with-jags-modules=MOD_PATH
+                          the location of the JAGS modules
 
 _ACEOF
 ac_status=$?
@@ -1634,32 +1628,18 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
 
-
-
-# Check whether --with-jags was given.
-if test "${with_jags+set}" = set; then
-  withval=$with_jags; JAGS_ROOT=$withval
-fi
-
-
-if ! test -z "${JAGS_ROOT}"; then
-   export PKG_CONFIG_PATH=${JAGS_ROOT}:$PKG_CONFIG_PATH
-fi
-
-
-
-if test "x$ac_cv_env_PKG_CONFIG_set" != "xset"; then
-	if test -n "$ac_tool_prefix"; then
-  # Extract the first word of "${ac_tool_prefix}pkg-config", so it can be a program name with args.
-set dummy ${ac_tool_prefix}pkg-config; ac_word=$2
+if test "x$prefix" = xNONE; then
+  echo $ECHO_N "checking for prefix by $ECHO_C" >&6
+  # Extract the first word of "jags", so it can be a program name with args.
+set dummy jags; ac_word=$2
 { echo "$as_me:$LINENO: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
-if test "${ac_cv_path_PKG_CONFIG+set}" = set; then
+if test "${ac_cv_path_ac_prefix_program+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
-  case $PKG_CONFIG in
+  case $ac_prefix_program in
   [\\/]* | ?:[\\/]*)
-  ac_cv_path_PKG_CONFIG="$PKG_CONFIG" # Let the user override the test with a path.
+  ac_cv_path_ac_prefix_program="$ac_prefix_program" # Let the user override the test with a path.
   ;;
   *)
   as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
@@ -1669,7 +1649,7 @@ do
   test -z "$as_dir" && as_dir=.
   for ac_exec_ext in '' $ac_executable_extensions; do
   if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
-    ac_cv_path_PKG_CONFIG="$as_dir/$ac_word$ac_exec_ext"
+    ac_cv_path_ac_prefix_program="$as_dir/$ac_word$ac_exec_ext"
     echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
     break 2
   fi
@@ -1680,189 +1660,132 @@ IFS=$as_save_IFS
   ;;
 esac
 fi
-PKG_CONFIG=$ac_cv_path_PKG_CONFIG
-if test -n "$PKG_CONFIG"; then
-  { echo "$as_me:$LINENO: result: $PKG_CONFIG" >&5
-echo "${ECHO_T}$PKG_CONFIG" >&6; }
+ac_prefix_program=$ac_cv_path_ac_prefix_program
+if test -n "$ac_prefix_program"; then
+  { echo "$as_me:$LINENO: result: $ac_prefix_program" >&5
+echo "${ECHO_T}$ac_prefix_program" >&6; }
 else
   { echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6; }
 fi
 
 
-fi
-if test -z "$ac_cv_path_PKG_CONFIG"; then
-  ac_pt_PKG_CONFIG=$PKG_CONFIG
-  # Extract the first word of "pkg-config", so it can be a program name with args.
-set dummy pkg-config; ac_word=$2
-{ echo "$as_me:$LINENO: checking for $ac_word" >&5
-echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
-if test "${ac_cv_path_ac_pt_PKG_CONFIG+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  case $ac_pt_PKG_CONFIG in
-  [\\/]* | ?:[\\/]*)
-  ac_cv_path_ac_pt_PKG_CONFIG="$ac_pt_PKG_CONFIG" # Let the user override the test with a path.
-  ;;
-  *)
-  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
-for as_dir in $PATH
-do
-  IFS=$as_save_IFS
-  test -z "$as_dir" && as_dir=.
-  for ac_exec_ext in '' $ac_executable_extensions; do
-  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
-    ac_cv_path_ac_pt_PKG_CONFIG="$as_dir/$ac_word$ac_exec_ext"
-    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
-    break 2
+  if test -n "$ac_prefix_program"; then
+    prefix=`$as_dirname -- "$ac_prefix_program" ||
+$as_expr X"$ac_prefix_program" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
+	 X"$ac_prefix_program" : 'X\(//\)[^/]' \| \
+	 X"$ac_prefix_program" : 'X\(//\)$' \| \
+	 X"$ac_prefix_program" : 'X\(/\)' \| . 2>/dev/null ||
+echo X"$ac_prefix_program" |
+    sed '/^X\(.*[^/]\)\/\/*[^/][^/]*\/*$/{
+	    s//\1/
+	    q
+	  }
+	  /^X\(\/\/\)[^/].*/{
+	    s//\1/
+	    q
+	  }
+	  /^X\(\/\/\)$/{
+	    s//\1/
+	    q
+	  }
+	  /^X\(\/\).*/{
+	    s//\1/
+	    q
+	  }
+	  s/.*/./; q'`
+    prefix=`$as_dirname -- "$prefix" ||
+$as_expr X"$prefix" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
+	 X"$prefix" : 'X\(//\)[^/]' \| \
+	 X"$prefix" : 'X\(//\)$' \| \
+	 X"$prefix" : 'X\(/\)' \| . 2>/dev/null ||
+echo X"$prefix" |
+    sed '/^X\(.*[^/]\)\/\/*[^/][^/]*\/*$/{
+	    s//\1/
+	    q
+	  }
+	  /^X\(\/\/\)[^/].*/{
+	    s//\1/
+	    q
+	  }
+	  /^X\(\/\/\)$/{
+	    s//\1/
+	    q
+	  }
+	  /^X\(\/\).*/{
+	    s//\1/
+	    q
+	  }
+	  s/.*/./; q'`
   fi
-done
-done
-IFS=$as_save_IFS
-
-  ;;
-esac
 fi
-ac_pt_PKG_CONFIG=$ac_cv_path_ac_pt_PKG_CONFIG
-if test -n "$ac_pt_PKG_CONFIG"; then
-  { echo "$as_me:$LINENO: result: $ac_pt_PKG_CONFIG" >&5
-echo "${ECHO_T}$ac_pt_PKG_CONFIG" >&6; }
+
+
+#Set optional include path with option --with-jags-include or
+#environment variable JAGS_INCLUDE
+
+
+# Check whether --with-jags-include was given.
+if test "${with_jags_include+set}" = set; then
+  withval=$with_jags_include; jags_include_path=$withval
+fi
+
+if test  -n "$jags_include_path"  ; then
+   JAGS_INCLUDE=${jags_include_path}
 else
-  { echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6; }
-fi
-
-  if test "x$ac_pt_PKG_CONFIG" = x; then
-    PKG_CONFIG=""
-  else
-    case $cross_compiling:$ac_tool_warned in
-yes:)
-{ echo "$as_me:$LINENO: WARNING: In the future, Autoconf will not detect cross-tools
-whose name does not start with the host triplet.  If you think this
-configuration is useful to you, please write to autoconf@gnu.org." >&5
-echo "$as_me: WARNING: In the future, Autoconf will not detect cross-tools
-whose name does not start with the host triplet.  If you think this
-configuration is useful to you, please write to autoconf@gnu.org." >&2;}
-ac_tool_warned=yes ;;
-esac
-    PKG_CONFIG=$ac_pt_PKG_CONFIG
-  fi
-else
-  PKG_CONFIG="$ac_cv_path_PKG_CONFIG"
-fi
-
-fi
-if test -n "$PKG_CONFIG"; then
-	_pkg_min_version=0.9.0
-	{ echo "$as_me:$LINENO: checking pkg-config is at least version $_pkg_min_version" >&5
-echo $ECHO_N "checking pkg-config is at least version $_pkg_min_version... $ECHO_C" >&6; }
-	if $PKG_CONFIG --atleast-pkgconfig-version $_pkg_min_version; then
-		{ echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6; }
-	else
-		{ echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6; }
-		PKG_CONFIG=""
-	fi
-
-fi
-
-pkg_failed=no
-{ echo "$as_me:$LINENO: checking for JAGS" >&5
-echo $ECHO_N "checking for JAGS... $ECHO_C" >&6; }
-
-if test -n "$PKG_CONFIG"; then
-    if test -n "$JAGS_CFLAGS"; then
-        pkg_cv_JAGS_CFLAGS="$JAGS_CFLAGS"
-    else
-        if test -n "$PKG_CONFIG" && \
-    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"jags = \$PACKAGE_VERSION\"") >&5
-  ($PKG_CONFIG --exists --print-errors "jags = $PACKAGE_VERSION") 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; then
-  pkg_cv_JAGS_CFLAGS=`$PKG_CONFIG --cflags "jags = $PACKAGE_VERSION" 2>/dev/null`
-else
-  pkg_failed=yes
-fi
-    fi
-else
-	pkg_failed=untried
-fi
-if test -n "$PKG_CONFIG"; then
-    if test -n "$JAGS_LIBS"; then
-        pkg_cv_JAGS_LIBS="$JAGS_LIBS"
-    else
-        if test -n "$PKG_CONFIG" && \
-    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"jags = \$PACKAGE_VERSION\"") >&5
-  ($PKG_CONFIG --exists --print-errors "jags = $PACKAGE_VERSION") 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; then
-  pkg_cv_JAGS_LIBS=`$PKG_CONFIG --libs "jags = $PACKAGE_VERSION" 2>/dev/null`
-else
-  pkg_failed=yes
-fi
-    fi
-else
-	pkg_failed=untried
-fi
-
-if test $pkg_failed = yes; then
-
-if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
-        _pkg_short_errors_supported=yes
-else
-        _pkg_short_errors_supported=no
-fi
-        if test $_pkg_short_errors_supported = yes; then
-	        JAGS_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "jags = $PACKAGE_VERSION"`
-        else
-	        JAGS_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "jags = $PACKAGE_VERSION"`
-        fi
-	# Put the nasty error message in config.log where it belongs
-	echo "$JAGS_PKG_ERRORS" >&5
-
-	{ { echo "$as_me:$LINENO: error: Package requirements (jags = $PACKAGE_VERSION) were not met:
-
-$JAGS_PKG_ERRORS
-
-Consider adjusting the PKG_CONFIG_PATH environment variable if you
-installed software in a non-standard prefix.
-" >&5
-echo "$as_me: error: Package requirements (jags = $PACKAGE_VERSION) were not met:
-
-$JAGS_PKG_ERRORS
-
-Consider adjusting the PKG_CONFIG_PATH environment variable if you
-installed software in a non-standard prefix.
-" >&2;}
+   if test  -z "${JAGS_INCLUDE}"  ; then
+      if test  "$prefix" == "NONE" ; then
+         { { echo "$as_me:$LINENO: error: \"JAGS headers not found. Use --with-jags-include configure option\"" >&5
+echo "$as_me: error: \"JAGS headers not found. Use --with-jags-include configure option\"" >&2;}
    { (exit 1); exit 1; }; }
-elif test $pkg_failed = untried; then
-	{ { echo "$as_me:$LINENO: error: The pkg-config script could not be found or is too old.  Make sure it
-is in your PATH or set the PKG_CONFIG environment variable to the full
-path to pkg-config.
+      else
+         JAGS_INCLUDE=${prefix}/include/JAGS
+      fi
+   fi
+fi
 
-To get pkg-config, see <http://pkg-config.freedesktop.org/>.
-See \`config.log' for more details." >&5
-echo "$as_me: error: The pkg-config script could not be found or is too old.  Make sure it
-is in your PATH or set the PKG_CONFIG environment variable to the full
-path to pkg-config.
+#Set optional library path with option --with-jags-lib or
+#environment variable JAGS_LIBS
 
-To get pkg-config, see <http://pkg-config.freedesktop.org/>.
-See \`config.log' for more details." >&2;}
-   { (exit 1); exit 1; }; }
+
+# Check whether --with-jags-lib was given.
+if test "${with_jags_lib+set}" = set; then
+  withval=$with_jags_lib; jags_lib_path=$withval
+fi
+
+if test  -n "$jags_lib_path"  ; then
+   JAGS_LIB=$jags_lib_path
 else
-	JAGS_CFLAGS=$pkg_cv_JAGS_CFLAGS
-	JAGS_LIBS=$pkg_cv_JAGS_LIBS
-        { echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6; }
-	:
+   if test  -z "${JAGS_LIB}"  ; then
+      if test  "${prefix}" == "NONE"  ; then
+         { { echo "$as_me:$LINENO: error: \"JAGS library not found. Use --with-jags-lib configure option\"" >&5
+echo "$as_me: error: \"JAGS library not found. Use --with-jags-lib configure option\"" >&2;}
+   { (exit 1); exit 1; }; }
+      else
+         JAGS_LIB=${prefix}/lib
+      fi
+   fi
+fi
+
+#Finally, set optional module directory using --with-jags-modules or
+#environment variable JAGS_MODULES
+
+
+# Check whether --with-jags-modules was given.
+if test "${with_jags_modules+set}" = set; then
+  withval=$with_jags_modules; jags_mod_path=$withval
+fi
+
+if test  -n "$jags_mod_path"  ; then
+   JAGS_MODULES=$jags_mod_path
+else
+   if test  -z "${JAGS_MODULES}"  ; then
+      JAGS_MODULES=${JAGS_LIB}/JAGS/modules
+   fi
 fi
 
 
 
-JAGS_MODDIR=`$PKG_CONFIG --variable=moduledir jags`
 
 
 ac_config_files="$ac_config_files src/Makevars"
@@ -2532,10 +2455,10 @@ LIBS!$LIBS$ac_delim
 build_alias!$build_alias$ac_delim
 host_alias!$host_alias$ac_delim
 target_alias!$target_alias$ac_delim
-PKG_CONFIG!$PKG_CONFIG$ac_delim
-JAGS_CFLAGS!$JAGS_CFLAGS$ac_delim
-JAGS_LIBS!$JAGS_LIBS$ac_delim
-JAGS_MODDIR!$JAGS_MODDIR$ac_delim
+ac_prefix_program!$ac_prefix_program$ac_delim
+JAGS_INCLUDE!$JAGS_INCLUDE$ac_delim
+JAGS_LIB!$JAGS_LIB$ac_delim
+JAGS_MODULES!$JAGS_MODULES$ac_delim
 LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
@@ -3535,10 +3458,10 @@ LIBS!$LIBS$ac_delim
 build_alias!$build_alias$ac_delim
 host_alias!$host_alias$ac_delim
 target_alias!$target_alias$ac_delim
-PKG_CONFIG!$PKG_CONFIG$ac_delim
-JAGS_CFLAGS!$JAGS_CFLAGS$ac_delim
-JAGS_LIBS!$JAGS_LIBS$ac_delim
-JAGS_MODDIR!$JAGS_MODDIR$ac_delim
+ac_prefix_program!$ac_prefix_program$ac_delim
+JAGS_INCLUDE!$JAGS_INCLUDE$ac_delim
+JAGS_LIB!$JAGS_LIB$ac_delim
+JAGS_MODULES!$JAGS_MODULES$ac_delim
 LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
